public_dependencies =
import public_dependencies += libecs%lib{ecs}

private_dependencies = # Implementation dependencies.
#import xxxx_libs += libhello%lib{hello}

lib{scripts}: {hxx ixx txx cxx}{**} $private_dependencies $public_dependencies

hxx{export}@./: cxx.importable = false

# Build options.
#
cxx.poptions += "-I$out_root" "-I$src_root"

{hbmia obja}{*}: cxx.poptions += -DLIBECS_STATIC_BUILD
{hbmis objs}{*}: cxx.poptions += -DLIBECS_SHARED_BUILD

# Export options.
#
lib{ecs}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root"
  cxx.export.libs = $public_dependencies
}

liba{ecs}: cxx.export.poptions += -DLIBECS_STATIC
libs{ecs}: cxx.export.poptions += -DLIBECS_SHARED

# Install into the libecs/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install = include/libecs/
  install.subdirs = true
}
