public_dependencies = # Interface dependencies.
private_dependencies = # Implementation dependencies.
#import xxxx_libs += libhello%lib{hello}

lib{ecs}: {hxx ixx txx cxx}{** -version} hxx{version} $private_dependencies $public_dependencies

hxx{version}: in{version} $src_root/manifest

hxx{export}@./: cxx.importable = false

# Build options.
#
cxx.poptions += "-I$out_root" "-I$src_root"

{hbmia obja}{*}: cxx.poptions += -DLIBECS_STATIC_BUILD
{hbmis objs}{*}: cxx.poptions += -DLIBECS_SHARED_BUILD

# Export options.
#
lib{ecs}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root"
  cxx.export.libs = $public_dependencies
}

liba{ecs}: cxx.export.poptions += -DLIBECS_STATIC
libs{ecs}: cxx.export.poptions += -DLIBECS_SHARED

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
#
if $version.pre_release
  lib{ecs}: bin.lib.version = "-$version.project_id"
else
  lib{ecs}: bin.lib.version = "-$version.major.$version.minor"

# Install into the libecs/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install = include/libecs/
  install.subdirs = true
}
